# Generated by Django 4.2.5 on 2023-10-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ddf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
